In [1]:
import torch
from torch import nn
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
with open('/Users/n1r7/Downloads/PYTORCH_NOTEBOOKS/Data/shakespeare.txt','r',encoding='utf8') as f:
    text = f.read()

In [3]:
type(text)

str

In [4]:
text[:1000]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bud buriest thy content,\n  And tender churl mak'st waste in niggarding:\n    Pity the world, or else this glutton be,\n    To eat the world's due, by the grave and thee.\n\n\n                     2\n  When forty winters shall besiege thy brow,\n  And dig deep trenches in thy beauty's field,\n  Thy youth's proud livery so gazed on now,\n  Will be a tattered weed of small worth held:  \n  Then being asked, where all thy beauty lies,\n  Where all the treasure of thy lusty days;\n  To sa

In [5]:
print(text[:1000])


                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But as the riper should by time decease,
  His tender heir might bear his memory:
  But thou contracted to thine own bright eyes,
  Feed'st thy light's flame with self-substantial fuel,
  Making a famine where abundance lies,
  Thy self thy foe, to thy sweet self too cruel:
  Thou that art now the world's fresh ornament,
  And only herald to the gaudy spring,
  Within thine own bud buriest thy content,
  And tender churl mak'st waste in niggarding:
    Pity the world, or else this glutton be,
    To eat the world's due, by the grave and thee.


                     2
  When forty winters shall besiege thy brow,
  And dig deep trenches in thy beauty's field,
  Thy youth's proud livery so gazed on now,
  Will be a tattered weed of small worth held:  
  Then being asked, where all thy beauty lies,
  Where all the treasure of thy lusty days;
  To say within thine own deep su

In [6]:
len(text) # number of characters

5445609

In [7]:
# Encode text at character level

all_characters = set(text)

In [8]:
all_characters

{'\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}'}

In [9]:
len(all_characters)

84

In [10]:
# Create encoder that takes character and returns number
# Create decoder that takes number and returns character

In [11]:
# num ---> letter
# for pair in enumerate(all_characters):
#     print(pair)

decoder = dict(enumerate(all_characters))

In [12]:
decoder

{0: 'e',
 1: 'c',
 2: ')',
 3: 'U',
 4: '3',
 5: '.',
 6: 'r',
 7: 'A',
 8: 'V',
 9: 'm',
 10: 'B',
 11: '<',
 12: 'q',
 13: 'f',
 14: ' ',
 15: 'C',
 16: 'i',
 17: 'I',
 18: 'X',
 19: 'Q',
 20: 'T',
 21: ';',
 22: 'x',
 23: 'o',
 24: '[',
 25: 'h',
 26: '-',
 27: 'W',
 28: 'Y',
 29: 'b',
 30: 'w',
 31: '9',
 32: '1',
 33: '!',
 34: 'N',
 35: 'M',
 36: '}',
 37: 's',
 38: 'y',
 39: 'S',
 40: '&',
 41: '\n',
 42: 'v',
 43: 'L',
 44: '6',
 45: 'J',
 46: 'k',
 47: 'G',
 48: '8',
 49: 'F',
 50: '7',
 51: 'R',
 52: 'a',
 53: '2',
 54: '?',
 55: '`',
 56: 'H',
 57: "'",
 58: 'P',
 59: '|',
 60: 'n',
 61: 'p',
 62: 'D',
 63: '0',
 64: ',',
 65: '4',
 66: 'u',
 67: 'l',
 68: 'E',
 69: '>',
 70: 't',
 71: 'j',
 72: ']',
 73: 'K',
 74: '_',
 75: 'd',
 76: '(',
 77: '"',
 78: '5',
 79: 'g',
 80: ':',
 81: 'O',
 82: 'z',
 83: 'Z'}

In [13]:
# letter ---> num
encoder = {char: ind for ind,char in decoder.items()}

In [14]:
encoder

{'e': 0,
 'c': 1,
 ')': 2,
 'U': 3,
 '3': 4,
 '.': 5,
 'r': 6,
 'A': 7,
 'V': 8,
 'm': 9,
 'B': 10,
 '<': 11,
 'q': 12,
 'f': 13,
 ' ': 14,
 'C': 15,
 'i': 16,
 'I': 17,
 'X': 18,
 'Q': 19,
 'T': 20,
 ';': 21,
 'x': 22,
 'o': 23,
 '[': 24,
 'h': 25,
 '-': 26,
 'W': 27,
 'Y': 28,
 'b': 29,
 'w': 30,
 '9': 31,
 '1': 32,
 '!': 33,
 'N': 34,
 'M': 35,
 '}': 36,
 's': 37,
 'y': 38,
 'S': 39,
 '&': 40,
 '\n': 41,
 'v': 42,
 'L': 43,
 '6': 44,
 'J': 45,
 'k': 46,
 'G': 47,
 '8': 48,
 'F': 49,
 '7': 50,
 'R': 51,
 'a': 52,
 '2': 53,
 '?': 54,
 '`': 55,
 'H': 56,
 "'": 57,
 'P': 58,
 '|': 59,
 'n': 60,
 'p': 61,
 'D': 62,
 '0': 63,
 ',': 64,
 '4': 65,
 'u': 66,
 'l': 67,
 'E': 68,
 '>': 69,
 't': 70,
 'j': 71,
 ']': 72,
 'K': 73,
 '_': 74,
 'd': 75,
 '(': 76,
 '"': 77,
 '5': 78,
 'g': 79,
 ':': 80,
 'O': 81,
 'z': 82,
 'Z': 83}

In [15]:
encoded_text = np.array([encoder[char] for char in text])

In [16]:
encoded_text[:500]

array([41, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 32, 41, 14, 14, 49,  6, 23,  9, 14, 13, 52, 16,
        6,  0, 37, 70, 14,  1,  6,  0, 52, 70, 66,  6,  0, 37, 14, 30,  0,
       14, 75,  0, 37, 16,  6,  0, 14, 16, 60,  1,  6,  0, 52, 37,  0, 64,
       41, 14, 14, 20, 25, 52, 70, 14, 70, 25,  0,  6,  0, 29, 38, 14, 29,
        0, 52, 66, 70, 38, 57, 37, 14,  6, 23, 37,  0, 14,  9, 16, 79, 25,
       70, 14, 60,  0, 42,  0,  6, 14, 75, 16,  0, 64, 41, 14, 14, 10, 66,
       70, 14, 52, 37, 14, 70, 25,  0, 14,  6, 16, 61,  0,  6, 14, 37, 25,
       23, 66, 67, 75, 14, 29, 38, 14, 70, 16,  9,  0, 14, 75,  0,  1,  0,
       52, 37,  0, 64, 41, 14, 14, 56, 16, 37, 14, 70,  0, 60, 75,  0,  6,
       14, 25,  0, 16,  6, 14,  9, 16, 79, 25, 70, 14, 29,  0, 52,  6, 14,
       25, 16, 37, 14,  9,  0,  9, 23,  6, 38, 80, 41, 14, 14, 10, 66, 70,
       14, 70, 25, 23, 66, 14,  1, 23, 60, 70,  6, 52,  1, 70,  0, 75, 14,
       70, 23, 14, 70, 25

In [17]:
# One-hot encode the data

def one_hot_encoder(encoded_text,num_uni_chars):
    
    # encoded_text ---> batch of encoded text
    # num_uni_chars ---> len(set(text))
    
    # create placeholder for 0s
    one_hot = np.zeros((encoded_text.size,num_uni_chars))
    
    # convert data type so we can use pytorch
    one_hot = one_hot.astype(np.float32)
    
    # use fancy indexing to fill in the 1s at correct index location
    one_hot[np.arange(one_hot.shape[0]),encoded_text.flatten()] = 1.0
    
    one_hot = one_hot.reshape((*encoded_text.shape,num_uni_chars))
    
    return one_hot

In [18]:
# test one_hot_encoder
arr = np.array([1,2,0])
arr

array([1, 2, 0])

In [19]:
one_hot_encoder(arr,3)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

In [20]:
example_text = np.arange(10)
example_text

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
example_text.reshape((5,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [22]:
# Create batch generator function

def generate_batches(encoded_text,samp_per_batch=10,seq_len=50):
    
    # X : encoded text of length seq_len
    # Y : encoded text shifted by one
    
    # number of characters per batch
    char_per_batch = samp_per_batch * seq_len
    
    # how many batches can be made given the len of encoded text
    num_batches_avail = int(len(encoded_text)/char_per_batch)
    
    # cut off end of encoded text that won't fit evenly in a batch
    encoded_text = encoded_text[:num_batches_avail*char_per_batch]
    
    encoded_text = encoded_text.reshape((samp_per_batch,-1))
    
    for n in range(0,encoded_text.shape[1],seq_len):
        
        x = encoded_text[:,n:n+seq_len]
        
        # create zeros array same shape as x
        y = np.zeros_like(x)
        
        try:
            
            y[:,:-1] = x[:,1:]
            y[:,-1] = encoded_text[:,n+seq_len]
        
        except:
            y[:,:-1] = x[:,1:]
            y[:,-1] = encoded_text[:,0]
            
        yield x,y

In [23]:
sample_text = np.arange(20)
sample_text

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [24]:
batch_generator = generate_batches(sample_text,samp_per_batch=2,seq_len=5)

In [25]:
x,y = next(batch_generator)

In [26]:
x

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [27]:
y

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [28]:
# Create LSTM model

In [29]:
class CharModel(nn.Module):
    
    def __init__(self,all_chars,num_hidden=256,num_layers=4,drop_prob=0.5,use_gpu=False):
        
        super().__init__()
        
        self.drop_prob = drop_prob
        self.num_layers = num_layers
        self.num_hidden = num_hidden
        self.use_gpu = use_gpu
        
        self.all_chars = all_chars
        self.decoder = dict(enumerate(all_chars))
        self.encoder = {char:ind for ind,char in decoder.items()}
        
        self.lstm = nn.LSTM(len(self.all_chars),num_hidden,num_layers,dropout=drop_prob,batch_first=True)
        
        self.dropout = nn.Dropout(drop_prob)
        
        self.fc_linear = nn.Linear(num_hidden,len(self.all_chars))
    
    
    def forward(self,x,hidden):
        
        lstm_output,hidden = self.lstm(x,hidden)
        
        drop_output = self.dropout(lstm_output)
        
        drop_output = drop_output.contiguous().view(-1,self.num_hidden) # reshape for final layer
        
        final_out = self.fc_linear(drop_output)
        
        return final_out,hidden
    
    
    def hidden_state(self,batch_size):
        
        if self.use_gpu:
            
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda(),
                      torch.zeros(self.num_layers,batch_size,self.num_hidden).cuda())
        
        else:
            
            hidden = (torch.zeros(self.num_layers,batch_size,self.num_hidden),
                      torch.zeros(self.num_layers,batch_size,self.num_hidden))
        
        return hidden


In [30]:
model = CharModel(all_chars=all_characters,
                 num_hidden=512,
                 num_layers=3,
                 drop_prob=0.5,
                 use_gpu=False)

In [31]:
model

CharModel(
  (lstm): LSTM(84, 512, num_layers=3, batch_first=True, dropout=0.5)
  (dropout): Dropout(p=0.5)
  (fc_linear): Linear(in_features=512, out_features=84, bias=True)
)

In [32]:
total_param = []

for p in model.parameters():
    total_param.append(int(p.numel()))
    
print(total_param)
print("\n")
print(sum(total_param))

[172032, 1048576, 2048, 2048, 1048576, 1048576, 2048, 2048, 1048576, 1048576, 2048, 2048, 43008, 84]


5470292


In [33]:
optimizer = torch.optim.Adam(model.parameters(),lr=0.001)
criterion = nn.CrossEntropyLoss()

In [34]:
train_percent = 0.1

train_ind = int(len(encoded_text)*train_percent)

train_data = encoded_text[:train_ind]
val_data = encoded_text[train_ind:]

In [35]:
len(train_data)

544560

In [36]:
len(val_data)

4901049

In [37]:
train_percent = 0.9

In [38]:
int(len(encoded_text) * train_percent)

4901048

In [39]:
# Train the model

In [40]:
# Variables

epochs = 60
batch_size = 100

seq_len = 100

tracker = 0

num_char = max(encoded_text)+1

In [ ]:
# Set model to train
model.train()


# Check to see if using GPU
if model.use_gpu:
    model.cuda()

for i in range(epochs):
    
    hidden = model.hidden_state(batch_size)
    
    
    for x,y in generate_batches(train_data,batch_size,seq_len):
        
        tracker += 1
        
        # One Hot Encode incoming data
        x = one_hot_encoder(x,num_char)
        
        # Convert Numpy Arrays to Tensor
        
        inputs = torch.from_numpy(x)
        targets = torch.from_numpy(y)
        
        # Adjust for GPU if necessary
        
        if model.use_gpu:
            
            inputs = inputs.cuda()
            targets = targets.cuda()
            
        # Reset Hidden State
        # If we dont' reset we would backpropagate through all training history
        hidden = tuple([state.data for state in hidden])
        
        model.zero_grad()
        
        lstm_output, hidden = model.forward(inputs,hidden)
        loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
        loss.backward()
        
        # POSSIBLE EXPLODING GRADIENT PROBLEM!
        # LET"S CLIP JUST IN CASE
        nn.utils.clip_grad_norm_(model.parameters(),max_norm=5)
        
        optimizer.step()
        
        
        
        ###################################
        ### CHECK ON VALIDATION SET ######
        #################################
        
        if tracker % 25 == 0:
            
            val_hidden = model.hidden_state(batch_size)
            val_losses = []
            model.eval()
            
            for x,y in generate_batches(val_data,batch_size,seq_len):
                
                # One Hot Encode incoming data
                x = one_hot_encoder(x,num_char)
                

                # Convert Numpy Arrays to Tensor

                inputs = torch.from_numpy(x)
                targets = torch.from_numpy(y)

                # Adjust for GPU if necessary

                if model.use_gpu:

                    inputs = inputs.cuda()
                    targets = targets.cuda()
                    
                # Reset Hidden State
                # If we dont' reset we would backpropagate through 
                # all training history
                val_hidden = tuple([state.data for state in val_hidden])
                
                lstm_output, val_hidden = model.forward(inputs,val_hidden)
                val_loss = criterion(lstm_output,targets.view(batch_size*seq_len).long())
        
                val_losses.append(val_loss.item())
            
            # Reset to training model after val for loop
            model.train()
            
            print(f"Epoch: {i} Step: {tracker} Val Loss: {val_loss.item()}")

Epoch: 0 Step: 25 Val Loss: 3.189283847808838
Epoch: 0 Step: 50 Val Loss: 3.1906490325927734
